### ISSUE TITLE
comple引入出现跟support包冲突的问题

### ISSUE THREAD

**Issue by Glorylan** [hust201010701/XRadarView#3]
border-width 重名 用Module导入可以手动修改名字，但是还是会报错。

**Comment by wl386123298** [comment]
是有这个问题，border-width重复了！

**Comment by hust201010701** [comment]
你们app中的build.gradle中的配置的版本是什么，麻烦贴出来看下。

**Comment by wl386123298** [comment]
v7的版本是25.4.0

**Comment by WZRRRRRR** [comment]
我也遇到这个问题了,怎么解决呢

**Comment by wl386123298** [comment]
引入源码，手动改咯！

**Comment by hust201010701** [comment]
1.0.5版本已经解决冲突问题。原来的borderWidth替换为boundaryWidth。
