### ISSUE TITLE
请问怎么设置一行可以显示4-6个字？

### ISSUE THREAD

**Issue by dengbing0907** [hust201010701/XRadarView#8]
设置固定的宽高，现在只显示2个字就换行了

**Comment by dengbing0907** [comment]
设置充满全屏也就显示3个字换行

**Comment by hust201010701** [comment]
这个是因为文字换行是我用DynamicLayout做的，你们不能控制。
这样吧，晚上我回去优化下，让你们也可以来自由控制行数。

**Comment by dengbing0907** [comment]
为什么我把title，values传过去还报空指针错误？
 if (values == null || values[i] == null) {
                    ss = new SpannableString(titles[i]);
                } else {
                    ss = new SpannableString(titles[i] + "\n" + values[i]);
                }
